### ISSUE TITLE
Redundant if check

### ISSUE THREAD

**Issue by digijap** [sud0woodo/python-reddit-cnc#1]
>  if bool(reddit_login) is True:

>  if bool(reddit_login):

Does the same thing :)

https://github.com/sud0woodo/python-reddit-cnc/blob/d01edb215deef12d6460fbddb5387466a191a320/reddit_command.py#L104

https://github.com/sud0woodo/python-reddit-cnc/blob/d01edb215deef12d6460fbddb5387466a191a320/reddit_command.py#L91

**Comment by sud0woodo** [comment]
thanks for the headsup! fixed it
